name: Test Matrix
on: ['pull_request']
jobs:
  PR-tests-linux:
    strategy:
      fail-fast: false
      matrix:
        runner: [
          'swift:5.2-xenial', 'swift:5.2-bionic',
          'swiftlang/swift:nightly-5.2-xenial', 'swiftlang/swift:nightly-5.2-bionic',
          'swiftlang/swift:nightly-5.3-xenial', 'swiftlang/swift:nightly-5.3-bionic',
          'swiftlang/swift:nightly-master-xenial', 'swiftlang/swift:nightly-master-bionic',
          'swiftlang/swift:nightly-master-focal',
          'swiftlang/swift:nightly-master-centos8',
          'swiftlang/swift:nightly-master-amazonlinux2'
        ]
        include:
          - installcmd: 'apt-get -q update && apt-get -q install -y libsqlite3-dev'
          - { 'runner': 'swiftlang/swift:nightly-master-centos8', 'installcmd': 'dnf install -y zlib-devel sqlite-devel' }
          - { 'runner': 'swiftlang/swift:nightly-master-amazonlinux2', 'installcmd': 'yum install -y zlib-devel sqlite-devel' }
    container: ${{ matrix.runner }}
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: ${{ matrix.installcmd }}
      - name: Update AmazonLinux2's too-old SQLite
        if: ${{ endsWith(matrix.runner, 'amazonlinux2') }}
        working-directory: /root
        # Cribbed from the Fedora RPM, leaves out a lot. System's Tcl is too old to run SQLite's tests.
        run: |
          yum install -y file tcl-devel make
          curl -L 'https://www.sqlite.org/src/tarball/sqlite.tar.gz?r=release' | tar xz && cd sqlite
          export CFLAGS="-DSQLITE_DISABLE_DIRSYNC=1 -DSQLITE_SECURE_DELETE=1"
          ./configure --prefix=/usr --libdir=/usr/lib64 --enable-fts3 --enable-all --with-tcl=/usr/lib64
          make all install
      - name: Check out code
        uses: actions/checkout@v2
      - name: Run tests with Thread Sanitizer
        run: swift test --enable-test-discovery --sanitize=thread
  PR-tests-macos:
    runs-on: macos-latest
    steps:
      - name: Select latest available Xcode
        uses: maxim-lobanov/setup-xcode@1.0
        with: { 'xcode-version': 'latest' }
      - name: Check out code
        uses: actions/checkout@v2
      - name: Run tests with Thread Sanitizer
        run: swift test --enable-test-discovery --sanitize=thread
